.TH sysfetch 1 "25 Nov 2025" "sysfetch 0.65"
.SH NAME
sysfetch
.SH SYNOPSIS
sysfetch [options]
.SH DESCRIPTION
Simple tool written in C to fetch basic system information like uptime, packages installed and CPU model.
.SH OPTIONS
.IP -h
show help message
.IP -v
show version details
.IP -s
print information with banner
.SH AUTHOR
Moritz Büttner (https://github.com/M0S4YSH3LL0)
